### ISSUE TITLE
check serializer info

### ISSUE THREAD

**Issue by demovirus** [alsyundawy/Microsoft-Office-For-MacOS#10]
README.md said that Microsoft Office 2019 Volume License Serializer is compatible with Maximum High Sierra. I don't think so. Yes, it doesn't work with office 16.69+, but I could succesfully applied it to the last 2019 version without 365 - 16.68 on Monterey 12.6.7.
16.68 file - Microsoft_Office_16.68.22121100_Installer.pkg
16.69 file - Microsoft_365_and_Office_16.69.23010700_Installer.pkg

**Comment by alsyundawy** [comment]
thx, update readme
