### ISSUE TITLE
Someone sell this tool on Rakuten

### ISSUE THREAD

**Issue by JeromeGsq** [alsyundawy/Microsoft-Office-For-MacOS#12]
More a questioin than an issue. 
I wanted to buy a Microsoft Office 2021 key on rakuten and when I received the installation instructions, I saw that the seller had sent me an executable named "Microsoft_Office_LTSC_2021_VL_Serializer (2).pkg" which shares the same MD5 hash as this github. 
Is this legal? 
He assures me that he has paid for access to this official Microsoft tool. 
Can you give me more information on the legality of selling this github tool? What kind of license is contained in this executable?

Thanks !

**Comment by alsyundawy** [comment]
is pirate thx
