### ISSUE TITLE
is it still working 

### ISSUE THREAD

**Issue by adiu45** [alsyundawy/Microsoft-Office-For-MacOS#13]
my system version is Ventura 13.2, intell chip, when I download [office installer](https://s.id/12HI9), it gives me a 2023 office. and after i run the removal and serializer, it still needs a office account.

**Comment by reidsneo** [comment]
At first I occured same issue,
I tested on sonoma M2 chip working great, 
but you need to run microsoft office reset afterward, check word, excel, point then it working
