### ISSUE TITLE
Mac Office 2021 not working on M2 MacBook Pro

### ISSUE THREAD

**Issue by Nhapsie** [alsyundawy/Microsoft-Office-For-MacOS#16]
MacOs: Sonoma 14.1.2

Problem: Sign-in pop up window on all apps. 

What I used: 
`Microsoft_Office_License_Removal_2.7`
`Microsoft_365_and_Office_16.79.23111019_Installer`
`Microsoft_Office_LTSC_2021_VL_Serializer`

**Comment by alsyundawy** [comment]
1. install Microsoft_Office_LTSC_2021_VL_Serializer
2. install Microsoft_365_and_Office_16.79.23111019_Installer
3. run any app office then click skip sign in.

**Comment by Nhapsie** [comment]
I did the process again, as you said. But there is no way to skip the sign-in window. When I close it, the apps don't load.

**Comment by alsyundawy** [comment]
At first I occured same issue,
I tested on sonoma M2 chip working great,
but you need to run microsoft office reset afterward, check word, excel, point then it working

**Comment by Nhapsie** [comment]
It is now working! Problem was the lack of rebooting the macOS.

**Comment by surya7765** [comment]
<img width="570" alt="Screenshot 2024-03-10 at 7 55 20 PM" src="https://github.com/alsyundawy/Microsoft-Office-For-MacOS/assets/47697392/f12ac489-10c0-4985-a021-7ff659ba19f8">

I'm still getting this page on startup.
