### ISSUE TITLE
Pop-up SignUp/SignIn page on startup on MAC M1 Air.

### ISSUE THREAD

**Issue by surya7765** [alsyundawy/Microsoft-Office-For-MacOS#18]
Steps I've followed:-

1. Microsoft_Office_LTSC_2021_VL_Serializer.pkg
2. Microsoft_365_and_Office_16.77.23091003_Installer.pkg
3. Restarted the system.
4. Microsoft_Office_License_Removal_2.7.pkg

Please guide me through the process if there's anything wrong I'm doing.
I only want to use excel and PowerPoint.

**Comment by Shinji3rd** [comment]
Why would you use the license removal after the installation? That one is a tool to remove any remnants of a previous install.
Repeat the process using the license removal tool first, then use the serializer, and after that run the installer. Everything will work fine that way,

**Comment by surya7765** [comment]
> Why would you use the license removal after the installation? That one is a tool to remove any remnants of a previous install. Repeat the process using the license removal tool first, then use the serializer, and after that run the installer. Everything will work fine that way,

Still, it's showing the SignIn page for me.
