### ISSUE TITLE
Activation is not working with Mac OSX Sonomo 14.4 on M2 Pro

### ISSUE THREAD

**Issue by drpshtiwan** [alsyundawy/Microsoft-Office-For-MacOS#20]
I tried to activate Microsoft Office on Mac OSX Sonomo 14.4 but was unsuccessful here is how I tried.

1- Install Microsoft Office 2021 LTSC Volume License Serializer 
2- Install Office 365 Suite Installer

But was not successful. I have another computer with Mac OSX Sonomo 14.1  there is no problem with this version.

I am using Macbook Pro M2 Pro. As I see only there is a problem with version 14.4 (Latest for now)

How can I activate it?

Thanks

**Comment by JasonMing** [comment]
Same issue to me.

After install Office 365 and Serializer

1. require login on first startup, cannot skip
2. after login, will enter into readonly/restricted mode, seems licenser not working
3. click the 「activate」 button has no any effects

**Comment by alsyundawy** [comment]
the issue maybe need new licennse, just waitinng for update

**Comment by alsyundawy** [comment]
try this

https://github.com/alsyundawy/Microsoft-Office-For-MacOS/raw/master/DATA/SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO

**Comment by JasonMing** [comment]
> try this
> 
> https://github.com/alsyundawy/Microsoft-Office-For-MacOS/raw/master/DATA/SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO

This is work!

**Comment by drpshtiwan** [comment]
Still not working with my computer. 
![Screenshot 2024-04-09 at 7 06 54 AM](https://github.com/alsyundawy/Microsoft-Office-For-MacOS/assets/6718949/1672c409-0ade-4045-96be-3f8d06839e70)

**Comment by JasonMing** [comment]
> Still not working with my computer.

@drpshtiwan Try to follow the steps in the README.

1. clean up the old version of office
2. run license removal to remove the old license
3. install office 16.78 
4. run the latest serializer [SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO](https://github.com/alsyundawy/Microsoft-Office-For-MacOS/raw/master/DATA/SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO)

**Comment by drpshtiwan** [comment]
> > Still not working with my computer.
> 
> @drpshtiwan Try to follow the steps in the README.
> 
> 1. clean up the old version of office
> 2. run license removal to remove the old license
> 3. install office 16.78
> 4. run the latest serializer [SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO](https://github.com/alsyundawy/Microsoft-Office-For-MacOS/raw/master/DATA/SW_DVD5_Office_Mac_Serializer_2021_MLF_X22-74226.ISO)

Can you provide me the download link of 16.78?

**Comment by JasonMing** [comment]
> * install office 16.78

@drpshtiwan sorry, my mistake, this step should be "install office 16.**83**"
<img width="370" alt="image" src="https://github.com/alsyundawy/Microsoft-Office-For-MacOS/assets/1220848/5a0fad61-b9e2-41cc-8e27-e1a43238a212">

The office 16.77 is present in the README.md
<img width="921" alt="image" src="https://github.com/alsyundawy/Microsoft-Office-For-MacOS/assets/1220848/ef72a6a0-a691-48b8-b71e-5e7a9c72e321">

You can also find all history versions listed at https://macadmins.software/office_history.xml

**Comment by alsyundawy** [comment]
closed , Update ReadMe
