### ISSUE TITLE
Activation impossible

### ISSUE THREAD

**Issue by Guilouz** [alsyundawy/Microsoft-Office-For-MacOS#21]
I'm currently stuck on activation.

I'm running macOS Sonoma 14.5 beta 3 (iMac Intel Core i9). It was working fine until installing the latest version 16.84.

I tested several versions without success: 16.84, 16.77, 16.78.3

With all Serializer types available:

Microsoft Office 2024 LTSC (Preview) Volume License Serializer
Microsoft Office 2016, 2019 & 2021 Activator / License_Serializer (MSDN ISO too)

And the activation does not go through, I am still asked to identify myself and no license is found, still read-only.
Even if I try to go back to an old version, the same thing.

I used License Removal Tool of course.

Any ideas?

**Comment by alsyundawy** [comment]
https://github.com/alsyundawy/Microsoft-Office-For-MacOS/issues?q=is%3Aissue+is%3Aclosed

& RTFM

**Comment by Guilouz** [comment]
@alsyundawy Already checked closed issue, nothing work as described in my issue.

Tested all possible serializer, cleaning licence with License Removal Tool between each test.

**Comment by Guilouz** [comment]
Version 16.85 doesn't work better either

**Comment by alsyundawy** [comment]
https://prnt.sc/vM2CKqJLFroR

**Comment by Guilouz** [comment]
@alsyundawy Why closing it ? It's not working.

How to explain nothing is working ?

I have tested _Microsoft Office 2024 LTSC (Preview) Volume License Serializer_ **and** _Microsoft Office 2016, 2019 & 2021 Activator / License_Serializer_ (MSDN ISO too)

Cleaned licence between each test with License Removal Tool.

Nothing is working on macOS Sonoma with Intel chip.

Can you give me the step to be working ?
