### ISSUE TITLE
Word and excel files (on the desktop) close on their own after a few seconds

### ISSUE THREAD

**Issue by freepalnow** [alsyundawy/Microsoft-Office-For-MacOS#22]
Hi
I had an old version of Office downloaded in 2021. A few days ago it started giving problems: after opening a word or excel file it immediately closed on its own. 
After trying to install and reinstall office, libre office etc., today I installed 'Microsoft Office LTSC 2021 Suite Installer Volume License Version 16.85 (24051214)' then 'Microsoft AutoUpdate (MAU) Standalone Installer 4.71' and finally 'Microsoft Office 2024 LTSC (Preview) Volume License Serializer'. 
Now, now, the activation was successful, it works but I have the same problem:
when i open the files **present in the desktop**, or create one in that location, THEY CLOSE THEMSELVES IMMEDIATELY AFTER. If I create them in a folder or removable media they work. 
I would like to point out that I installed on macOS Sonoma 14.5.
Do you have an idea how to solve it? 
Thank you

**Comment by alsyundawy** [comment]
sorry ist for office & activatio only, case closed

https://prnt.sc/vM2CKqJLFroR
