### ISSUE TITLE
Microsoft Sign-In?

### ISSUE THREAD

**Issue by smoledavid** [alsyundawy/Microsoft-Office-For-MacOS#25]
Hello,

just have a quick question. I expect that the answer is going to be no, but Is it possible to log in with this activation?

Thanks once more for answering.

**Comment by YuhApps** [comment]
> Hello,
> 
> just have a quick question. I expect that the answer is going to be no, but Is it possible to log in with this activation?
> 
> Thanks once more for answering.

Of course.

**Comment by smoledavid** [comment]
Oh thanks for the answer. How does the activation works then?

**Comment by YuhApps** [comment]
You simply install the VL Serializer then open an Office app. That's all. Nothing else to be done.
