### ISSUE TITLE
Can't keep the menu bar always show

### ISSUE THREAD

**Issue by OrangeLee03** [alsyundawy/Microsoft-Office-For-MacOS#27]
When I installed the "Microsoft_Office_LTSC_2024_VL_Serializer.pkg" ,even I set the menu bar always show in the System Setting. The menu bar can't always show when I open Word.app in full screen mode (Other app won't happen ,like PowerPoint ,Excel etc.).If my Microsoft 356 is not activated ,this phenomenon won't happen.
# Set "Automatically hide and show the menu bar "-never
<img width="827" alt="Screenshot 2024-12-09 at 18 30 30" src="https://github.com/user-attachments/assets/b79edd84-9b61-458d-9f9d-e7f37657f757">

# Not Activated
The menu bar can always show.
<img width="1920" alt="Screenshot 2024-12-09 at 18 17 34" src="https://github.com/user-attachments/assets/f669a5c6-aece-4ddf-b66b-0f57473d6c3e">

# After install the "Microsoft_Office_LTSC_2024_VL_Serializer.pkg"
The menu bar will disappear when I remove the pointer from it.
<img width="1920" alt="Screenshot 2024-12-09 at 18 18 45" src="https://github.com/user-attachments/assets/a626a28d-52ae-4ffb-a89d-2886928acf8a">

**Comment by alsyundawy** [comment]
ask to microsoft

**Comment by YuhApps** [comment]
Simply log out and log in back to your Mac. This is an Apple issue.
