### ISSUE TITLE
MacBook Pro M1 

### ISSUE THREAD

**Issue by kx3kx3kx3** [alsyundawy/Microsoft-Office-For-MacOS#3]
with MacBook Pro m1 and macOS Ventura v13.0 the serializer doesn't work and  ask me always activation

**Comment by alsyundawy** [comment]
already use 2021 license?

**Comment by kx3kx3kx3** [comment]
yes

**Comment by alsyundawy** [comment]
wait update from upstream, after done i will upload & update.

thx
