### ISSUE TITLE
How to update after installation?

### ISSUE THREAD

**Issue by Laicure** [alsyundawy/Microsoft-Office-For-MacOS#4]
First of all, thanks for this! It works well without any issues!

---
I have installed both successfully.
But after that, it cannot be updated anymore (via _Check for Updates_).

Do I need to redownload and install the 2GB Office365 installer file to get the updated version?

**Comment by alsyundawy** [comment]
if you have latest macos, is autoupdate

**Comment by Laicure** [comment]
I'm on the latest Ventura.

Before activating, it can be updated but now, after activating, it shows this whenever I check for updates:
![image](https://user-images.githubusercontent.com/8619566/223342306-479dcca5-5369-4021-90fe-ae10b38f1daf.png)

**Comment by Laicure** [comment]
Edit:

My bad, I turned the "Open at Login" entries for Office and I got that error:
Fixed after doing this:
![image](https://user-images.githubusercontent.com/8619566/223346749-9086cc46-e70e-4d65-a4ca-5e6e2eba145f.png)

**Comment by alsyundawy** [comment]
case closed
