### ISSUE TITLE
How to activate it on Catalina?

### ISSUE THREAD

**Issue by void285** [alsyundawy/Microsoft-Office-For-MacOS#5]
Hello, I installed `Microsoft Office 2019/LTSC 2021 Suite Installer Volume License Version 16.66.1 Maximum 10.15.x (Catalina)` on Catalina and login with my hotmail account, but office is not activated, I tried Word and found it's readonly now.

I what to know what I may have missed, or I misunderstood the aim of this repo, I expect it activated after installation.

**Comment by alsyundawy** [comment]
dont login then install office license 2019

**Comment by void285** [comment]
Thanks, I focus on the README and forgot to download the repo data, I have activate the software.
