### ISSUE TITLE
Activating on M2 Macbook Air

### ISSUE THREAD

**Issue by aravindun** [alsyundawy/Microsoft-Office-For-MacOS#7]
I installed [Microsoft Office 2019 / LTSC 2021 / Office 365 Suite Installer](https://s.id/12HI9) and [Microsoft Office 2019 Volume License Serializer (M1/M1 PRO/M1 MAX/M1 ULTRA/M2 Support)](https://s.id/1d4hh). However, the product is not activated and I am able to open only in read only mode. Can you please tell me how to activate?

**Comment by alsyundawy** [comment]
install serializer 2021 first then office
