### ISSUE TITLE
 How to activate Microsoft 365 on lastest MacOS?

### ISSUE THREAD

**Issue by yanpeng** [alsyundawy/Microsoft-Office-For-MacOS#8]
hi, 

after downloading the [Microsoft Office 2019 / LTSC 2021 / Office 365 Suite Installer](https://s.id/12HI9) and the lastest office 2021 LTSC Serializer.pkg, I installed this Serializer.pkg firstly, then office installer. But when I opened Microsoft Word, it still required me to sign in Microsoft Account, is there a way to activate Microsoft 365 on the lastest MacOS?

**Comment by alsyundawy** [comment]
dont have skip login ?

**Comment by yanpeng** [comment]
> dont have skip login ?

this login window cannot skip unless you close it, so I think I failed to activate Microsoft 365.

**Comment by yanpeng** [comment]
> same problem here with macOS Ventura. I have tried Office 2019, 2021 and 365, also with the help of Office-Reset 1.9.1 and License Removal Tool 2.7, but still can't activate....

I can always activate Office 2021 LTSC (but I don't try Office 2019), never failed to activate except Microsoft 364. you run the License Removal tool 2.7, uninstall the old copy, install new copy, at last run the serializer.

**Comment by alsyundawy** [comment]
https://github.com/alsyundawy/Microsoft-Office-For-MacOS/blob/master/README.md
